# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
apt_packages:
  - infernal
  - hmmer
addons:
  homebrew:
    taps: brewsci/bio
    packages:
        - infernal
        - hmmer
before_script:
  - wget https://microbiology.se/sw/ITSx_1.1.2.tar.gz -O /tmp/ITSx.tar.gz
  - tar -xvf /tmp/ITSx.tar.gz -C /tmp
  - export PATH=$PATH:/tmp/ITSx_1.1.2
r:
    - oldrel
    - bioc-release
    - bioc-devel
os:
    - linux
    - osx
jobs:
    allow-failures:
        - r: bioc-devel
    include:
        - r: bioc-release
          bioc_packages:
            - BiocCheck
            - ShortRead
          bioc_check: true
          after_success: Rscript -e 'covr::codecov()'
